export * from './main.screen'
export * from './main/main-about.section'
export * from './main/main-collaboration.section'
export * from './main/main-contact.section'
export * from './main/main-knowledge.section'
export * from './main/main-projects.section'
