export const ABOUT_ANCHOR = 'sobre'
export const KNOWLEDGE_ANCHOR = 'conhecimento'
export const PROJECTS_ANCHOR = 'projetos'
export const COLLABORATION_ANCHOR = 'colaboracao'
export const CONTACT_ANCHOR = 'contato'
